/** First-party plugins that ship INSIDE the lm-assist package ("bundled plugins").
 *
 *  ── Why this exists ───────────────────────────────────────────────────────────────
 *  Every ext plugin so far reached a node by a human `cp` from the plugin's own repo,
 *  because nothing in the package ever carried a payload. That is the same split that
 *  bites the pane shims (`docs/ui-panes-deploy.md`): the code rides the build, the
 *  payload rides a person, and the mismatch only surfaces later. A first-party plugin
 *  has no reason to be distributed by hand — it can travel in the tarball with Core.
 *
 *  ── The trust argument, stated honestly ───────────────────────────────────────────
 *  Contract §2 makes enabling a loopback-only HUMAN action because enabling authorises
 *  THIRD-PARTY code execution. A bundled payload is different in exactly one way that
 *  matters: it arrived in the same npm artifact as Core itself. Someone who could
 *  tamper with it could equally tamper with `core/dist`, which needs no approval at
 *  all — so a second consent prompt for code the operator already installed buys no
 *  security, it only guarantees the plugin is dead on every fresh node until someone
 *  remembers to click.
 *
 *  What the checksum in `bundled.json` therefore DOES buy is narrower, and it is the
 *  only claim made here: a plugin directory auto-enables ONLY while it is byte-for-byte
 *  the payload this build shipped. A locally edited tree — the case the pin was built
 *  for — never inherits that trust; it falls back to the normal human gate.
 *
 *  ── What is deliberately NOT automatic ────────────────────────────────────────────
 *  - A tree we did not seed, or one that drifted from what we seeded, is never
 *    overwritten and never auto-enabled. Local edits win over the package.
 *  - An owner who disables a bundled plugin stays in charge: `bundledOptOut` is sticky
 *    across upgrades (otherwise every upgrade would silently undo their decision).
 *  - Grants are DERIVED from config this node already holds, never shipped. No secret
 *    is ever written into the package.
 */
import * as fs from 'fs';
import * as path from 'path';
import { payloadChecksum, manifestDigest } from './checksum';
import { pluginsDir, pluginStateFile } from './paths';
import { readState, writeState } from './state-store';
import { validateManifest } from './manifest';
import {
  bundledPluginsEnabled, MANIFEST_FILENAME, MAX_PLUGIN_NAME, SEGMENT_RE, type PluginManifest,
} from './model';

/** One entry of `core/data/mcp-plugins/bundled.json`, regenerated by
 *  `core/scripts/gen-bundled-plugins.js` whenever a vendored payload changes. */
export interface BundledEntry {
  name: string;
  version: string;
  /** Payload checksum of the vendored tree, computed by the SAME `payloadChecksum()`
   *  the loader pins with — a divergence here would silently stop every auto-enable. */
  checksum: string;
  /** Digest of the vendored manifest. Indexed separately because the payload checksum
   *  cannot cover `mcp-plugin.json`: without this, the shipped manifest — the review
   *  surface that DECLARES the plugin's capabilities — would be the one part of the
   *  package no pin protects. */
  manifestDigest: string;
  /** Present when this payload is a MIRROR of a plugin maintained in another repo —
   *  which is every plugin here today. `checksum` is the upstream payload hash it was
   *  vendored from, so `gen-bundled-plugins.js` can refuse an edit made to lm-assist's
   *  copy instead of silently forking a repo we do not own. Absent would mean a plugin
   *  lm-assist itself owns.
   *
   *  🔴 CHECKSUM ONLY — deliberately no repo URL, name, or author. This file is published
   *  to a public repo and to npm, and an upstream may be PRIVATE; naming it would disclose
   *  the repository (and the account behind it) to everyone who installs lm-assist. The
   *  hash is all the enforcement needs: whoever maintains the plugin already knows where
   *  it lives, and nobody else should learn it from here. */
  upstream?: { checksum: string };
}

export interface BundledIndex {
  plugins: BundledEntry[];
}

export type SeedOutcome =
  | 'seeded'            // directory did not exist -> installed from the package
  | 'updated'           // the tree we previously seeded was replaced by a newer one
  | 'up-to-date'        // already exactly this payload
  | 'kept-local'        // a tree we did not seed (or one edited since) -> left alone
  | 'skipped';          // subsystem off, or the package entry is unusable

export interface SeedResult {
  name: string;
  version: string;
  outcome: SeedOutcome;
  /** Whether this pass turned the plugin on (and therefore changed the tool surface). */
  enabled: boolean;
  /** Env names filled from local config this pass. NAMES ONLY — never values. */
  grantedEnv: string[];
  detail?: string;
}

export interface SeedOptions {
  /** Override the vendored payload root (tests). */
  sourceDir?: string;
  /** Override the install root (tests). Defaults to the node's plugins dir. */
  targetDir?: string;
  /** Override the state file (tests). Also suppresses connector sync at call sites. */
  stateFile?: string;
  /** Injected hub config, so a test never reads the real `~/.lm-assist/hub.json`. */
  hubConfig?: { hubUrl?: string; apiKey?: string };
  /** Skip the auto-enable step and only place files (used by `--check`). */
  seedOnly?: boolean;
  /** Report what WOULD happen without touching the disk. */
  dryRun?: boolean;
}

/** The vendored payload root inside the package: `core/data/mcp-plugins/`.
 *  `__dirname` is `core/dist/mcp-server/plugins` in both a repo build and an npm
 *  install, so the same relative hop resolves in both. */
export function bundledSourceDir(): string {
  return path.join(__dirname, '..', '..', '..', 'data', 'mcp-plugins');
}

/** The index is a PACKAGE file — it cannot change while the process runs, and
 *  `view()` consults it for every plugin on every list call. Memoise per source dir so
 *  the review page never pays a disk read per row. */
const indexCache = new Map<string, BundledIndex>();

export function _resetBundledIndexCacheForTests(): void { indexCache.clear(); }

export function readBundledIndex(sourceDir = bundledSourceDir()): BundledIndex {
  const cached = indexCache.get(sourceDir);
  if (cached) return cached;
  const parsed = parseBundledIndex(sourceDir);
  indexCache.set(sourceDir, parsed);
  return parsed;
}

function parseBundledIndex(sourceDir: string): BundledIndex {
  try {
    const raw = JSON.parse(fs.readFileSync(path.join(sourceDir, 'bundled.json'), 'utf8')) as unknown;
    const plugins = (raw as BundledIndex)?.plugins;
    if (!Array.isArray(plugins)) return { plugins: [] };
    return {
      plugins: plugins.filter(
        (p): p is BundledEntry =>
          !!p && typeof p.name === 'string' && typeof p.version === 'string'
          && typeof p.checksum === 'string' && typeof p.manifestDigest === 'string'
          // The name becomes a path component. Hold it to the SAME grammar the loader
          // enforces for a plugin id, so a malformed index can never address a
          // directory outside the plugins root.
          && SEGMENT_RE.test(p.name) && p.name.length <= MAX_PLUGIN_NAME,
      ),
    };
  } catch {
    return { plugins: [] };   // no index shipped => nothing is bundled (fail closed)
  }
}

// --- grant derivation -------------------------------------------------------------

/** Derive a bundled plugin's declared env from configuration the node ALREADY has.
 *  A provider returns only names it can fill honestly; anything it cannot derive is
 *  left for a human `POST /mcp-plugins/<name>/grant`. */
type GrantProvider = (opts: SeedOptions) => Record<string, string>;

/**
 * `langmart-design` talks to the LangMart PUBLIC API (`/api/*` on the gateway).
 * Both values it needs are already on the node in `~/.lm-assist/hub.json`:
 *
 *  - the hub api key is an ordinary account key for the same user and organisation, so
 *    the gateway accepts it on `/api/*` like any other. Verified against the live API,
 *    not inferred from the shape of the string.
 *  - the api origin is the hub origin with the `assist-api.` host swapped for `api.`,
 *    which keeps dev and prod self-selecting instead of hardcoded.
 *
 * NOTE treat the granted key as FULLY PRIVILEGED for its account. Read-only is a
 * property of the PLUGIN, which hardcodes GET — never relax that on the assumption that
 * the credential itself is narrowly scoped.
 */
const langmartDesignGrants: GrantProvider = (opts) => {
  const hub = opts.hubConfig ?? loadHubConfigSafely();
  const out: Record<string, string> = {};
  const base = deriveLangmartApiBase(hub.hubUrl);
  if (base) out.LANGMART_API_BASE = base;
  if (hub.apiKey) out.LANGMART_API_KEY = hub.apiKey;
  // All-or-nothing: half a grant produces a plugin that starts and then fails every
  // call with a confusing auth error, which is worse than staying unconfigured.
  return out.LANGMART_API_BASE && out.LANGMART_API_KEY ? out : {};
};

/** `wss://assist-api.langmart.ai` -> `https://api.langmart.ai`. Returns null rather
 *  than guessing when the hub host is not one we recognise — a wrong base URL would
 *  send the node's api key to a host nobody reviewed. */
export function deriveLangmartApiBase(hubUrl?: string): string | null {
  if (!hubUrl) return null;
  let u: URL;
  try { u = new URL(hubUrl); } catch { return null; }
  if (!u.hostname.startsWith('assist-api.')) return null;
  return `https://api.${u.hostname.slice('assist-api.'.length)}`;
}

function loadHubConfigSafely(): { hubUrl?: string; apiKey?: string } {
  try {
    // Required lazily: this module is imported by the seeder CLI, and hub-config
    // fingerprints the machine on load.
    const { getHubConfig } = require('../../hub-client/hub-config');
    const cfg = getHubConfig();
    return { hubUrl: cfg?.hubUrl, apiKey: cfg?.apiKey };
  } catch {
    return {};
  }
}

const GRANT_PROVIDERS: Record<string, GrantProvider> = {
  'langmart-design': langmartDesignGrants,
};

// --- seeding ----------------------------------------------------------------------

function copyTree(src: string, dst: string): void {
  fs.mkdirSync(dst, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, e.name);
    const to = path.join(dst, e.name);
    // Mirrors payloadChecksum(): a symlink can never be part of a payload we pin.
    if (e.isSymbolicLink()) throw new Error(`symlink in bundled payload: ${from}`);
    if (e.isDirectory()) { copyTree(from, to); continue; }
    if (!e.isFile()) throw new Error(`unsupported file type in bundled payload: ${from}`);
    fs.copyFileSync(from, to);
  }
}

/** Remove files the new payload no longer ships, so the installed tree is exactly the
 *  package's tree (a leftover file changes the checksum and would block auto-enable). */
function pruneExtraneous(src: string, dst: string): void {
  for (const e of fs.readdirSync(dst, { withFileTypes: true })) {
    const inDst = path.join(dst, e.name);
    const inSrc = path.join(src, e.name);
    if (!fs.existsSync(inSrc)) { fs.rmSync(inDst, { recursive: true, force: true }); continue; }
    if (e.isDirectory()) pruneExtraneous(inSrc, inDst);
  }
}

/** Identity of a plugin tree as the loader sees it: the payload hash AND the manifest
 *  digest. Both are needed — `payloadChecksum()` skips `mcp-plugin.json` by design, so
 *  a manifest-only release (new version, reworded tools, a widened `capabilities.env`)
 *  moves the digest and leaves the checksum untouched. */
interface TreeIdentity { payload: string; manifest: string | null }

function treeIdentity(dir: string): TreeIdentity {
  return { payload: payloadChecksum(dir), manifest: rawManifestDigest(dir) };
}

function rawManifestDigest(dir: string): string | null {
  try {
    return manifestDigest(JSON.parse(fs.readFileSync(path.join(dir, MANIFEST_FILENAME), 'utf8')));
  } catch {
    return null;   // unreadable/not JSON => never "the same as" anything
  }
}

function sameTree(a: TreeIdentity, b: { payload: string | null; manifest: string | null }): boolean {
  return a.manifest !== null && b.manifest !== null && a.payload === b.payload && a.manifest === b.manifest;
}

function readManifest(dir: string): PluginManifest | null {
  try {
    const raw = JSON.parse(fs.readFileSync(path.join(dir, MANIFEST_FILENAME), 'utf8'));
    const v = validateManifest(raw, { dirName: path.basename(dir) });
    return v.ok ? v.manifest : null;
  } catch {
    return null;
  }
}

/**
 * Install + trust the bundled plugins for THIS node. Safe to call on every boot: it is
 * a no-op once each payload is in place, and it never overwrites a tree it did not put
 * there.
 */
export function seedBundledPlugins(opts: SeedOptions = {}): SeedResult[] {
  if (!bundledPluginsEnabled()) return [];

  const sourceRoot = opts.sourceDir ?? bundledSourceDir();
  const targetRoot = opts.targetDir ?? pluginsDir();
  const stateFile = opts.stateFile ?? pluginStateFile();
  const index = readBundledIndex(sourceRoot);
  const out: SeedResult[] = [];

  for (const entry of index.plugins) {
    try {
      out.push(seedOne(entry, sourceRoot, targetRoot, stateFile, opts));
    } catch (e) {
      out.push({
        name: entry.name, version: entry.version, outcome: 'skipped',
        enabled: false, grantedEnv: [], detail: (e as Error).message,
      });
    }
  }
  return out;
}

function seedOne(
  entry: BundledEntry, sourceRoot: string, targetRoot: string, stateFile: string, opts: SeedOptions,
): SeedResult {
  const src = path.join(sourceRoot, entry.name);
  const dst = path.join(targetRoot, entry.name);
  const base = { name: entry.name, version: entry.version, grantedEnv: [] as string[] };

  if (!fs.existsSync(path.join(src, MANIFEST_FILENAME))) {
    return { ...base, outcome: 'skipped', enabled: false, detail: 'bundled payload is missing its manifest' };
  }

  // The index must agree with the bytes actually shipped. If a payload was edited
  // without regenerating bundled.json, refuse the whole plugin rather than seed a
  // tree whose "trusted" checksum was never true.
  const srcId = treeIdentity(src);
  const srcChecksum = srcId.payload;
  if (srcChecksum !== entry.checksum || srcId.manifest !== entry.manifestDigest) {
    return {
      ...base, outcome: 'skipped', enabled: false,
      detail: `bundled.json is stale: package payload is ${srcChecksum}/${srcId.manifest}, ` +
              `index says ${entry.checksum}/${entry.manifestDigest} — run core/scripts/gen-bundled-plugins.js`,
    };
  }

  const state = readState(entry.name, stateFile);
  const exists = fs.existsSync(path.join(dst, MANIFEST_FILENAME));
  const installed = exists ? safeIdentity(dst) : null;

  let outcome: SeedOutcome;
  if (exists && installed === null) {
    // Present but unhashable (a symlink in the tree, an unreadable file). We cannot
    // prove it is ours, so it is not ours to replace.
    return { ...base, outcome: 'kept-local', enabled: false, detail: 'the installed payload could not be hashed — left untouched' };
  }
  if (!exists) {
    outcome = 'seeded';
  } else if (sameTree(srcId, installed!)) {
    outcome = 'up-to-date';
  } else if (sameTree(
    { payload: state.bundledSeededChecksum ?? '', manifest: state.bundledSeededManifestDigest ?? null },
    installed!,
  )) {
    outcome = 'updated';            // still exactly what WE put there -> ours to replace
  } else {
    // Either a hand-installed plugin that happens to share the name, or our payload
    // with local edits. Both are a human's tree; the package does not get to win.
    return {
      ...base, outcome: 'kept-local', enabled: false,
      detail: 'the installed payload is not the one this package seeded — left untouched',
    };
  }

  if (opts.dryRun) {
    return { ...base, outcome, enabled: false, detail: 'dry run — nothing written' };
  }

  if (outcome !== 'up-to-date') {
    copyTree(src, dst);
    if (outcome === 'updated') pruneExtraneous(src, dst);
    const after = treeIdentity(dst);
    if (!sameTree(srcId, after)) {
      return { ...base, outcome: 'skipped', enabled: false, detail: `copy landed as ${after.payload}/${after.manifest}, expected ${srcChecksum}/${srcId.manifest}` };
    }
  }
  writeState(entry.name, {
    bundledSeededChecksum: srcChecksum,
    bundledSeededManifestDigest: srcId.manifest ?? undefined,
  }, stateFile);

  if (opts.seedOnly) return { ...base, outcome, enabled: false };

  // --- grants: fill declared names from local config, never overwrite a human's ---
  const manifest = readManifest(dst);
  const granted: string[] = [];
  if (manifest) {
    const provider = GRANT_PROVIDERS[entry.name];
    const derived = provider ? provider(opts) : {};
    const declared = new Set(manifest.capabilities.env);
    const existing = readState(entry.name, stateFile).grants ?? {};
    const grants: Record<string, string> = { ...existing };
    for (const [k, v] of Object.entries(derived)) {
      if (!declared.has(k)) continue;          // an undeclared grant is refused everywhere else too
      if (existing[k] !== undefined) continue; // a value a human set outranks a derived one
      grants[k] = v;
      granted.push(k);
    }
    if (granted.length > 0) writeState(entry.name, { grants }, stateFile);
  }

  // --- trust: auto-enable only while the tree IS the package's payload ---
  const cur = readState(entry.name, stateFile);
  if (cur.bundledOptOut) {
    return { ...base, outcome, enabled: false, grantedEnv: granted, detail: 'owner disabled this plugin; leaving it off' };
  }
  const alreadyLive = cur.enabled
    && cur.approvedPayloadChecksum === srcChecksum
    && cur.approvedManifestDigest === srcId.manifest;
  if (alreadyLive) {
    return { ...base, outcome, enabled: false, grantedEnv: granted };
  }
  if (!manifest) {
    return { ...base, outcome, enabled: false, grantedEnv: granted, detail: 'manifest failed validation — not enabled' };
  }
  // A plugin whose declared env is not fully granted would spawn and fail every call.
  const missing = manifest.capabilities.env.filter((k) => (cur.grants ?? {})[k] === undefined);
  if (missing.length > 0) {
    return {
      ...base, outcome, enabled: false, grantedEnv: granted,
      detail: `not enabled: ${missing.join(', ')} not granted — POST /mcp-plugins/${entry.name}/grant, then enable`,
    };
  }

  const rawManifest = JSON.parse(fs.readFileSync(path.join(dst, MANIFEST_FILENAME), 'utf8'));
  writeState(entry.name, {
    enabled: true,
    approvedPayloadChecksum: srcChecksum,
    approvedManifestDigest: manifestDigest(rawManifest),
    enabledAt: Date.now(),
    // Honest provenance: the /mcp-tools panel must not show this as a person's click.
    enabledBy: `bundled@${entry.version}`,
    revertedReason: undefined,
    health: { failures: 0 },
  }, stateFile);

  return { ...base, outcome, enabled: true, grantedEnv: granted };
}

function safeIdentity(dir: string): TreeIdentity | null {
  try { return treeIdentity(dir); } catch { return null; }
}

/** True when this plugin name ships inside the package (drives the UI's badge and the
 *  routes' opt-out bookkeeping). */
export function isBundledPlugin(name: string, sourceDir?: string): boolean {
  return readBundledIndex(sourceDir ?? bundledSourceDir()).plugins.some((p) => p.name === name);
}

/** True when this bundled plugin is a MIRROR of a payload maintained in another repo,
 *  so the review screen can say "don't edit this here". Deliberately a boolean and not
 *  the upstream's identity — see `BundledEntry.upstream`. */
export function isBundledMirror(name: string, sourceDir?: string): boolean {
  return !!readBundledIndex(sourceDir ?? bundledSourceDir()).plugins.find((p) => p.name === name)?.upstream;
}

/** One-line-per-plugin summary for boot logs and the `core.sh plugins` CLI. */
export function formatSeedResults(results: SeedResult[]): string[] {
  return results.map((r) => {
    const bits = [`${r.name}@${r.version}`, r.outcome];
    if (r.enabled) bits.push('ENABLED');
    if (r.grantedEnv.length) bits.push(`granted:${r.grantedEnv.join('+')}`);
    if (r.detail) bits.push(`(${r.detail})`);
    return bits.join(' · ');
  });
}
