/**
 * DTO validation for terminal API.
 *
 * Routes pass req.body through these parsers before any handler logic. Every
 * parser:
 *   - rejects unknown / wrong-type fields with INVALID_INPUT
 *   - applies regex allowlists at the boundary (no shell injection downstream)
 *   - returns a typed object with sane defaults
 *
 * Why centralized: previously every route did its own typeof check and the
 * fields flowed straight to OS-level calls. Half the bugs in the original code
 * were "field X reached layer Y without ever being checked".
 */

import { TerminalError } from './errors';
import type {
  SendKeysInput, WaitForInput, CaptureInput,
  CCLaunchInput, CCPromptInput, CCPivotInput,
  SlashCommandInput, SelectChoiceInput,
  TabKind,
} from './types';

// ---------- Allowlist regexes (the security boundary) ---------------------

/** tmux session names: tmux itself rejects ':' and '.', we add length cap. */
const SESSION_NAME_RE = /^[A-Za-z0-9_-][A-Za-z0-9_.\-+ ]{0,127}$/;

/** Pane qualifier: window.pane or window only. NEVER allows a session name. */
const PANE_QUALIFIER_RE = /^\d+(\.\d+)?$/;

/** SSH target: user@host or just host. Strict allowlist for cmd safety. */
const SSH_TARGET_RE = /^[A-Za-z0-9_]+(@[A-Za-z0-9_.\-]+)?$/;

/** Path-ish: must be absolute, no shell metachars, no NUL. */
const ABS_PATH_RE = /^[\/A-Za-z][^\0;&|`$<>(){}*?"'\\]*$/;

/** Tab id: generated by us, but validate format on lookup. */
const TAB_ID_RE = /^tab-[a-z0-9]{8}$/;

/** Slash command name: only common identifier chars (CC's own commands match this). */
const SLASH_CMD_RE = /^[a-z][a-z0-9_-]{0,31}$/i;

// ---------- Helpers --------------------------------------------------------

function bad(message: string, details: Record<string, unknown> = {}): never {
  throw new TerminalError('INVALID_INPUT', message, details);
}

function asString(v: unknown, field: string, opts: { maxLen?: number; allowEmpty?: boolean } = {}): string {
  if (typeof v !== 'string') bad(`${field} must be a string`, { got: typeof v });
  const s = v as string;
  if (!opts.allowEmpty && s.length === 0) bad(`${field} must not be empty`);
  if (opts.maxLen && s.length > opts.maxLen) bad(`${field} exceeds ${opts.maxLen} chars`);
  return s;
}

function asOptString(v: unknown, field: string, opts: { maxLen?: number } = {}): string | null {
  if (v === undefined || v === null) return null;
  return asString(v, field, opts);
}

function asBool(v: unknown, field: string, def: boolean): boolean {
  if (v === undefined || v === null) return def;
  if (typeof v !== 'boolean') bad(`${field} must be a boolean`, { got: typeof v });
  return v as boolean;
}

function asInt(v: unknown, field: string, def: number, opts: { min?: number; max?: number } = {}): number {
  if (v === undefined || v === null) return def;
  if (typeof v !== 'number' || !Number.isFinite(v) || !Number.isInteger(v)) {
    bad(`${field} must be an integer`, { got: typeof v });
  }
  const n = v as number;
  if (opts.min !== undefined && n < opts.min) bad(`${field} must be >= ${opts.min}`);
  if (opts.max !== undefined && n > opts.max) bad(`${field} must be <= ${opts.max}`);
  return n;
}

function asStringArray(v: unknown, field: string): string[] {
  if (v === undefined || v === null) return [];
  if (!Array.isArray(v)) bad(`${field} must be an array`);
  return (v as unknown[]).map((x, i) => asString(x, `${field}[${i}]`, { maxLen: 256 }));
}

function matchRegex(value: string, re: RegExp, field: string, hint: string): string {
  if (!re.test(value)) bad(`${field} has invalid format (${hint})`, { value });
  return value;
}

// ---------- Public validators ---------------------------------------------

export function parseSessionName(name: string): string {
  return matchRegex(asString(name, 'name', { maxLen: 128 }), SESSION_NAME_RE, 'name', 'tmux session name');
}

export function parseTabId(id: string): string {
  return matchRegex(asString(id, 'id', { maxLen: 32 }), TAB_ID_RE, 'id', 'tab-xxxxxxxx');
}

export function parseAbsPath(p: unknown, field: string): string {
  const s = asString(p, field, { maxLen: 4096 });
  return matchRegex(s, ABS_PATH_RE, field, 'absolute path, no shell metachars');
}

export function parseOptAbsPath(p: unknown, field: string): string | null {
  if (p === undefined || p === null) return null;
  return parseAbsPath(p, field);
}

export function parseSshTarget(t: unknown, field: string): string {
  return matchRegex(asString(t, field, { maxLen: 256 }), SSH_TARGET_RE, field, 'user@host');
}

export function parsePaneQualifier(v: unknown): string | null {
  if (v === undefined || v === null) return null;
  return matchRegex(asString(v, 'paneQualifier', { maxLen: 16 }), PANE_QUALIFIER_RE, 'paneQualifier', 'N or N.M');
}

export function parseTabKind(v: unknown): TabKind {
  const s = asString(v, 'kind');
  if (s !== 'gnome' && s !== 'wt-ssh' && s !== 'tmux') {
    bad(`kind must be one of gnome|wt-ssh|tmux`, { got: s });
  }
  return s as TabKind;
}

export function parseSendKeys(body: unknown): SendKeysInput {
  const b = (body || {}) as Record<string, unknown>;
  return {
    keys: asString(b.keys, 'keys', { maxLen: 65536, allowEmpty: false }),
    literal: asBool(b.literal, 'literal', false),
    enter: asBool(b.enter, 'enter', false),
    paneQualifier: parsePaneQualifier(b.paneQualifier ?? b.target),
  };
}

export function parseWaitFor(body: unknown): WaitForInput {
  const b = (body || {}) as Record<string, unknown>;
  const pattern = asString(b.pattern, 'pattern', { maxLen: 4096, allowEmpty: false });
  const flags = asOptString(b.flags, 'flags', { maxLen: 8 }) ?? '';
  // Compile-test the regex up-front so the caller gets INVALID_INPUT, not a 500.
  if (!asBool(b.literal, 'literal', false)) {
    try { new RegExp(pattern, flags); }
    catch (e: unknown) { bad('pattern is not a valid regex', { pattern, flags, error: String(e) }); }
  }
  return {
    pattern,
    literal: asBool(b.literal, 'literal', false),
    flags,
    timeoutMs: asInt(b.timeoutMs, 'timeoutMs', 15000, { min: 1, max: 600000 }),
    pollMs: asInt(b.pollMs, 'pollMs', 200, { min: 50, max: 10000 }),
    paneQualifier: parsePaneQualifier(b.paneQualifier ?? b.target),
    lines: b.lines === undefined || b.lines === null ? null : asInt(b.lines, 'lines', 0, { min: 1, max: 10000 }),
  };
}

export function parseCapture(query: Record<string, string | undefined>): CaptureInput {
  return {
    paneQualifier: parsePaneQualifier(query.paneQualifier ?? query.target),
    lines: query.lines === undefined ? null : asInt(parseInt(query.lines, 10), 'lines', 0, { min: 1, max: 10000 }),
    start: query.start === undefined ? null : asInt(parseInt(query.start, 10), 'start', 0, { min: -100000, max: 100000 }),
  };
}

export function parseCCLaunch(body: unknown): CCLaunchInput {
  const b = (body || {}) as Record<string, unknown>;
  return {
    cwd: parseAbsPath(b.cwd, 'cwd'),
    model: asOptString(b.model, 'model', { maxLen: 64 }),
    extraFlags: asStringArray(b.extraFlags ?? b.flags, 'extraFlags'),
    skipPermissions: asBool(b.skipPermissions, 'skipPermissions', true),
    cols: asInt(b.cols, 'cols', 220, { min: 20, max: 1000 }),
    rows: asInt(b.rows, 'rows', 60, { min: 5, max: 500 }),
    readyPattern: asOptString(b.readyPattern, 'readyPattern', { maxLen: 256 }) ?? 'ctx:',
    readyTimeoutMs: asInt(b.readyTimeoutMs, 'readyTimeoutMs', 30000, { min: 1, max: 600000 }),
    autoAcceptTrust: asBool(b.autoAcceptTrust, 'autoAcceptTrust', true),
  };
}

export function parseCCPrompt(body: unknown): CCPromptInput {
  const b = (body || {}) as Record<string, unknown>;
  const text = asString(b.text, 'text', { maxLen: 65536, allowEmpty: false });
  const allowNewlines = asBool(b.allowNewlines, 'allowNewlines', false);
  if (!allowNewlines && /\r|\n/.test(text)) {
    bad('text contains a newline; CC submits on Enter and would split the prompt. Pass allowNewlines:true to override.');
  }
  return { text, allowNewlines };
}

export function parseSlash(body: unknown): SlashCommandInput {
  const b = (body || {}) as Record<string, unknown>;
  const cmd = matchRegex(asString(b.cmd, 'cmd', { maxLen: 32 }), SLASH_CMD_RE, 'cmd', 'identifier');
  const argsRaw = asOptString(b.args, 'args', { maxLen: 4096 });
  // Forbid newlines in args — slash commands are single-line.
  if (argsRaw && /\r|\n/.test(argsRaw)) bad('args must not contain newlines');
  return { cmd, args: argsRaw };
}

export function parseSelectChoice(body: unknown): SelectChoiceInput {
  const b = (body || {}) as Record<string, unknown>;
  return { n: asInt(b.n, 'n', 1, { min: 1, max: 9 }) };
}

export function parseCCPivot(body: unknown): CCPivotInput {
  const b = (body || {}) as Record<string, unknown>;
  return {
    // Session ID format varies (uuid, short id) — only enforce no shell metachars.
    newSessionId: matchRegex(
      asString(b.newSessionId, 'newSessionId', { maxLen: 128 }),
      /^[A-Za-z0-9_.-]+$/, 'newSessionId', 'alphanumeric/_/-/.',
    ),
    prompt: asString(b.prompt, 'prompt', { maxLen: 65536, allowEmpty: false }),
    promptPattern: asOptString(b.promptPattern, 'promptPattern', { maxLen: 256 }) ?? '❯',
    timeoutMs: asInt(b.timeoutMs, 'timeoutMs', 15000, { min: 1, max: 600000 }),
  };
}

/** Window-group label: must be a safe-for-title identifier. */
const WINDOW_GROUP_RE = /^[A-Za-z][A-Za-z0-9_-]{0,31}$/;

export function parseCreateTab(body: unknown): {
  kind: TabKind;
  title: string | null;
  cwd: string | null;
  command: string | null;
  tmuxSession: string | null;
  sshTarget: string | null;
  env: Record<string, string>;
  cols: number | null;
  rows: number | null;
  windowGroup: string;
} {
  const b = (body || {}) as Record<string, unknown>;
  const env: Record<string, string> = {};
  if (b.env !== undefined && b.env !== null) {
    if (typeof b.env !== 'object' || Array.isArray(b.env)) bad('env must be an object');
    for (const [k, v] of Object.entries(b.env as Record<string, unknown>)) {
      if (!/^[A-Z_][A-Z0-9_]*$/i.test(k)) bad(`env key ${k} invalid`);
      env[k] = asString(v, `env.${k}`, { maxLen: 4096 });
    }
  }
  // Default windowGroup = 'lm-assist'. All tabs sharing the same group
  // are forced into the same gnome-terminal window (see spawn-tabs.ts).
  // Pass a different value to open in a separate window (e.g. one group
  // for engines, one for monitoring), or pass null/empty to disable
  // grouping (each tab gets its own window — legacy behavior).
  let windowGroup = 'lm-assist';
  if (b.windowGroup !== undefined && b.windowGroup !== null) {
    if (b.windowGroup === '') {
      windowGroup = '';
    } else {
      windowGroup = matchRegex(asString(b.windowGroup, 'windowGroup', { maxLen: 32 }), WINDOW_GROUP_RE, 'windowGroup', 'identifier');
    }
  }
  return {
    kind: parseTabKind(b.kind),
    title: asOptString(b.title, 'title', { maxLen: 256 }),
    cwd: parseOptAbsPath(b.cwd, 'cwd'),
    command: asOptString(b.command, 'command', { maxLen: 4096 }),
    tmuxSession: b.tmuxSession === undefined || b.tmuxSession === null ? null : parseSessionName(b.tmuxSession as string),
    sshTarget: b.sshTarget === undefined || b.sshTarget === null ? null : parseSshTarget(b.sshTarget, 'sshTarget'),
    env,
    cols: b.cols === undefined || b.cols === null ? null : asInt(b.cols, 'cols', 0, { min: 20, max: 1000 }),
    rows: b.rows === undefined || b.rows === null ? null : asInt(b.rows, 'rows', 0, { min: 5, max: 500 }),
    windowGroup,
  };
}

export function parseCreateTmux(body: unknown): {
  name: string;
  cwd: string | null;
  cols: number | null;
  rows: number | null;
  command: string | null;
} {
  const b = (body || {}) as Record<string, unknown>;
  return {
    name: parseSessionName(asString(b.name, 'name')),
    cwd: parseOptAbsPath(b.cwd, 'cwd'),
    cols: b.cols === undefined || b.cols === null ? null : asInt(b.cols, 'cols', 0, { min: 20, max: 1000 }),
    rows: b.rows === undefined || b.rows === null ? null : asInt(b.rows, 'rows', 0, { min: 5, max: 500 }),
    command: asOptString(b.command, 'command', { maxLen: 4096 }),
  };
}
